import express, { Express } from 'express';
import { requireAuth } from './authMiddleware.js';
import './config.js'; // do not remove this line
import { createNote, getNotes, updateNote } from './controllers/NoteController.js';
import { createPet, getPet } from './controllers/PetController.js';
import { createPurchase, getPurchases } from './controllers/PurchaseController.js';
import { getAllShopItems, getShopItem } from './controllers/ShopItemController.js';
import {
  createStudyRoom,
  getAllStudyRooms,
  getStudyRoomById,
  joinStudyRoom,
} from './controllers/StudyRoomController.js';
import { createUser, getMe, getUserProfile, logIn, logOut } from './controllers/UserController.js';
import { sessionMiddleware } from './sessionConfig.js';

const app: Express = express();

app.use(sessionMiddleware); // Setup session management middleware
app.use(express.json()); // Setup JSON body parsing middleware
app.use(express.urlencoded({ extended: false })); // Setup urlencoded (HTML Forms) body parsing middleware

// Setup static resource file middleware
// This allows the client to access any file inside the `public` directory
// Only put file that you actually want to be publicly accessibly in the `public` folder
app.use(express.static('public', { extensions: ['html'] }));

// Serve the built Svelte frontend (generated by 'npm run build:client')
app.use(express.static('frontend/build'));

// -- Routes --------------------------------------------------
// Register your routes below this line

// Public routes
app.post('/api/users', createUser);
app.post('/api/login', logIn);
app.delete('/api/sessions', logOut);

// Protected routes
app.use('/api/users', requireAuth); // all /users routes after this need auth
app.get('/api/users/profile', getUserProfile);

app.use('/api/pets', requireAuth);
app.post('/api/pets', createPet);
app.get('/api/pets/:petId', getPet);

app.use('/api/notes', requireAuth);
app.get('/api/notes', getNotes);
app.post('/api/notes', createNote);
app.patch('/api/notes/:noteId', updateNote);

app.use('/api/shopItems', requireAuth);
app.get('/api/shopItems', getAllShopItems);
app.get('/api/shopItems/:itemId', getShopItem);

app.use('/api/purchases', requireAuth);
app.get('/api/purchases', getPurchases);
app.post('/api/purchases', createPurchase);

app.post('/api/rooms', createStudyRoom);
app.get('/api/rooms', getAllStudyRooms);
app.get('/api/rooms/:roomId', getStudyRoomById);
app.post('/api/rooms/join', joinStudyRoom);

// Returns the signed-in user (or 401). The frontend's auth store
// calls this on every page load.
app.get('/api/me', getMe);

// -- SPA fallback --------------------------------------------
// Keep these LAST, after every `/api/*` route.
// Any unmatched `/api/*` request gets a JSON-safe 404.
app.use('/api', (req, res) => {
  res.sendStatus(404);
});

// Any other unmatched request falls back to the Svelte app so
// client-side routing works on refresh.
app.use((req, res) => {
  res.sendFile('index.html', { root: 'frontend/build' });
});

app.listen(process.env.PORT, () => {
  console.log(`Server listening on http://localhost:${process.env.PORT}`);
});
